# Generated by Django 5.2.17 on 2026-09-05 19:42

import django.core.validators
import django.db.models.deletion
import news.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='news/covers/%Y/%m/', validators=[news.validators.validate_image_size], verbose_name='تصویر اصلی'),
        ),
        migrations.AlterField(
            model_name='news',
            name='body',
            field=models.TextField(blank=True, help_text='اگر از بخش\u200cهای محتوایی پایین صفحه استفاده می\u200cکنید، این قسمت را خالی بگذارید.', verbose_name='متن ساده خبر'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image_url',
            field=models.URLField(blank=True, help_text='تنها زمانی استفاده می\u200cشود که تصویر اصلی بارگذاری نشده باشد.', verbose_name='نشانی تصویر خارجی'),
        ),
        migrations.CreateModel(
            name='NewsAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=160, verbose_name='عنوان فایل')),
                ('file', models.FileField(upload_to='news/attachments/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'zip')), news.validators.validate_attachment_size], verbose_name='فایل')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان بارگذاری')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='news.news', verbose_name='خبر')),
            ],
            options={
                'verbose_name': 'فایل پیوست',
                'verbose_name_plural': 'فایل\u200cهای پیوست',
                'ordering': ('uploaded_at',),
            },
        ),
        migrations.CreateModel(
            name='NewsContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=1, help_text='عدد کمتر، بخش را بالاتر نمایش می\u200cدهد.', verbose_name='ترتیب نمایش')),
                ('text', models.TextField(blank=True, verbose_name='متن')),
                ('image', models.ImageField(blank=True, upload_to='news/content/%Y/%m/', validators=[news.validators.validate_image_size], verbose_name='تصویر میان\u200cمتن')),
                ('caption', models.CharField(blank=True, max_length=240, verbose_name='توضیح تصویر')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='news.news', verbose_name='خبر')),
            ],
            options={
                'verbose_name': 'بخش محتوایی',
                'verbose_name_plural': 'بخش\u200cهای محتوایی',
                'ordering': ('position', 'pk'),
            },
        ),
    ]
